#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2024.0.0b4post1"

# Which extras should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = ["navx"]

# Other pip packages to install
requires = ["robotpy-ctre==2024.0.0b4"]
