poetry add robotpy 
poetry add robotpy-apriltag 
poetry add robotpy-commands-v2 
poetry add robotpy-cscore 
poetry add robotpy-ctre 
poetry add robotpy-hal 
poetry add robotpy-halsim-ds-socket 
poetry add robotpy-halsim-gui 
poetry add robotpy-halsim-ws 
poetry add robotpy-installer 
poetry add robotpy-navx 
poetry add robotpy-pathplannerlib 
poetry add robotpy-photonvision 
poetry add robotpy-playingwithfusion 
poetry add robotpy-rev 
poetry add robotpy-wpilib-utilities 
poetry add robotpy-wpimath 
poetry add robotpy-wpinet 
poetry add robotpy-wpiutil 
poetry add wpilib 
