BUTTON_A = 1
BUTTON_B = 2
BUTTON_X = 3
BUTTON_Y = 4
BUTTON_LEFT_BUMPER = 5
BUTTON_RIGHT_BUMPER = 6
BUTTON_SELECT = 7
BUTTON_START = 8
BUTTON_LEFT_JOYSTICK = 9
BUTTON_RIGHT_JOYSTICK = 10

AXIS_LEFT_X = 0
AXIS_LEFT_Y = 1
AXIS_LEFT_TRIGGER = 2
AXIS_RIGHT_TRIGGER = 3
AXIS_RIGHT_X = 4
AXIS_RIGHT_Y = 5

POV_NOT_PRESSED = -1
POV_UP = 0
POV_UP_RIGHT = 45
POV_RIGHT = 90
POV_DOWN_RIGHT = 135
POV_DOWN = 180
POV_DOWN_LEFT = 225
POV_LEFT = 270
POV_UP_LEFT = 315
